### ISSUE TITLE
Areas in no neighborhood

### ISSUE THREAD

**Issue by larrykooper** [MusikAnimal/locality.nyc#1]
Hi! 
As a New York geography and history buff, I love your app.  

There are some areas that, on your map, are not part of any neighborhood. In Manhattan, for example, between 5th and 6th Avenues from 14th St to 20th St, and between Lexington and Park Avenues from 30th to 34th Streets. Those areas are occupied by homes and businesses and should be included in a neighborhood. Would you accept a pull request?

**Comment by MusikAnimal** [comment]
@larrykooper Wow, guess I never got the notification for this. Sorry it took so long to get back to you! Pull requests are gladly accepted, but for changes to the neighborhood data I'll kindly ask for a reference. The data I compiled was based on thorough research, and some areas I was unable to conclude exactly what neighborhood it was part of. Also not sure if you know how to build the data: I used Google's maps engine to draw the lines, expert to KML, and concert JSON. I've got the system down pat, so you can simply tell me what needs changing, along with a reference, and I'll happily implement it. Thanks!

**Comment by larrykooper** [comment]
Thanks! If I start working on that topic again I'll get back in touch.

**Comment by IllFapUM00s1k** [comment]
who spells kooper with a k lol like the kkk?

@uyscuti @FastLizard4 @oshwah @krenair @jianhui67 @datguy @pokefan95 @ks0stm @sagan @steinsplitter @justberry @cyberpower678 @fluffernutter @ksft @marktraceur @earwig @allthefoxes @alexz @samtar @keegan @cameron11598 @grumble @logan @l235 @samwalton9 @niko @tbloemink @revent @idoh @barras @e @k6ka @slakr @snowolf @notaspy @jackmcbarn @stwalkerster @deskana

**Comment by MusikAnimal** [comment]
Closing from inactivity. If you have any ideas on what neighborhoods those areas should be in, let me know! :)
